<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Authors>jumpyapple</Authors>
    <VersionPrefix>0.2.0</VersionPrefix>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Copyright>Copyright (C) 2025</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="AurieSharpInterop">
      <HintPath>..\..\..\..\..\projects\fields-of-mistria-modding\AurieSharp\x64\Release\AurieSharpInterop.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
